Algoritmo "soma dois numeros"

Var
// Seção de Declarações das variáveis 

     A : inteiro
     B, C : inteiro

Inicio

      //comando de saida
      escreva("Digite um numero: ")

      //comando de entrada
      leia(A)
      
      escreva("Digite um numero: ")
      leia(B)
      
      //processamento
      
       C <- A + B
       
       //fase saida de dados
       escreva(C)
       
      
Fimalgoritmo